### ISSUE TITLE
DB Table Prefixes aren't used

### ISSUE THREAD

**Issue by martinweber-info** [jmx2inc/picpuller-for-craft3#1]
If you use a **DB_TABLE_PREFIX** in your Craft 3 installation the Plugin throws an error after authentication due to a missing table.

Turns out that the prefix isn't used in the select query.

<img width="364" alt="bildschirmfoto 2018-01-31 um 18 25 17" src="https://user-images.githubusercontent.com/16985665/35637411-70917f02-06b4-11e8-943d-231896907b50.png">

In my case (DB_TABLE_PREFIX is set to "craft") the table name should be "craft_picpuller_authorizations"

**Comment by cavellblood** [comment]
I'm getting this error when I click on the **Authorized Users** tab in the plugin settings. I'm getting the following message:

> **Database Exception – yii\db\Exception**
>
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft3.users' doesn't exist
>
> The SQL being executed was: SELECT `craft_user_id`, `instagram_id`, `instagram_oauth`, `u`.`firstName`, `u`.`lastName`, `u`.`username`
> FROM `craft_picpuller_authorizations` `oauth`
> INNER JOIN `users` `u` ON oauth.craft_user_id=u.id
> ORDER BY `u`.`id`

Was this pull request also to fix the Authorized Users query? My table name is `craft3.craft_users`.

**Comment by martinweber-info** [comment]
Sorry, my fault. I totally overlooked the the table in the inner join and just tested with the personal license single user. So there was only one user.

A second pull request is on the way...

**Comment by cavellblood** [comment]
No worries. Thanks!
