### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by kaspar-allenbach** [jmx2inc/picpuller-for-craft3#10]
On this page: https://picpuller.com/code/media-recent your example code is wrong. it is `picPuller` not `picpuller`

**Comment by johnfmorton** [comment]
That page shows the docs for Pic Puller version 2. Pic Puller version 3 uses picPuller. It's mentioned in the Pic Puller 3 docs [here](https://github.com/jmx2inc/picpuller-for-craft3/blob/v3/PicPullerDocumentation.md#updating-from-version-2x). I'll add a note to the Pic Puller site to make that clearer. Thanks.
