### ISSUE TITLE
Use Picpuller as a fieldtype

### ISSUE THREAD

**Issue by kaspar-allenbach** [jmx2inc/picpuller-for-craft3#11]
I don't understand how to display an instagram image with the picpuller fieldtype.

![bildschirmfoto 2018-12-24 um 13 07 24](https://user-images.githubusercontent.com/762213/50399060-de64d500-077c-11e9-8079-8e3d161aba2f.png)

I Added a picpuller Fieldtype to a matrix field.

Now I try to call it in the template:

```
{% for block in entry.matrixContent.all() %}
  {% for asset in block.cellInstaGallery %}
    <img src="{{ asset.low_resolution }}">
  {% endfor %}
{% endfor %}
```

This does nothing. How do I have to call this?

**Comment by johnfmorton** [comment]
You'd use the `craft.picpuller.media` function if you're in Craft 2, but I think you're in Craft 3, so the `craft.picPuller.media` would be what you're looking for. Here's an example of just a single image being displayed in when the Image Browser was used (Craft 2 example):

https://picpuller.com/code/media-by-instagram-id

You will need to be sure you're using the `{cache}` and `{endcache}` tags in your Twig code as well. Every "hit" to the Instagram API reduces your API limit that Instagram allows. Currently, they allow 200 hits per hour. The cache tags will keep your API usage down.

Does that help?

**Comment by johnfmorton** [comment]
A quick take on what you'd probably do would look something like this:

```
{% cache %}
	{% for block in entry.matrixContent.all() %}
	  {% for asset in block.cellInstaGallery %}

		{% for instagramdata in craft.picPuller.media({'use_stale_cache' : TRUE, 'user_id' : 1, 'media_id': asset}) %}
		    {% if loop.first %}
		        <p>Status: {{ instagramdata.status }}</p>
		        <p>Error Type: {{ instagramdata.error_type }}</p>
		        <p>Error Message: {{ instagramdata.error_message }}</p>
		        <hr>
		    {% endif %}
		    {% if instagramdata.status == 'true' %}
		        <p>username: {{ instagramdata.username }}</p>
		        <p>full_name: {{ instagramdata.full_name }}</p>
		        <p><img src="{{instagramdata.low_resolution}}"></p>
		        <p>caption: {{instagramdata.caption}}</p>
		        <p>created_time: {{ instagramdata.created_time }}</p>
		    {% else %}

		        <p>Error Type: {{ instagramdata.error_type }}</p>
		        <p>Error Message: {{ instagramdata.error_message }}</p>
		    {% endif %}
		{% endfor %}


	  {% endfor %}
	{% endfor %}
{% endcache %}
```

**Comment by johnfmorton** [comment]
If you have other questions, please just post again. I’ll close the issue for now.
