### ISSUE TITLE
How does the limit work?

### ISSUE THREAD

**Issue by kaspar-allenbach** [jmx2inc/picpuller-for-craft3#12]
I use picpuller like this:
```

{% for instagramdata in craft.picPuller.media_recent({ 'user_id' : 1,  'use_stale_cache' : true, limit: null }) %}

    {% if instagramdata.status == 'true' %}

      {% if hashFilter in instagramdata.tags %}
        {% include '_atoms/instaImg' %}
      {% endif %}

    {% endif %}

  {% endfor %}
```

So images with only a certain hashtag are shown.

- This code only shows 3 images with the `limit: null` option.
- When I add `limit: 50` it shows 4 images.
- When I remove the limit option entirely, there are also only 3 images appearing ??

I don't see a pattern there. How does this work?

**Comment by kaspar-allenbach** [comment]
Hmm, interesting. If I remove the filter conditional then a lot more images show up.
So I suspect, the filter only applies to images with which the hashtag hasb been added on upload and not afterwards. I have to check that with my client.

**Comment by johnfmorton** [comment]
Sounds good. I’ll close this issue for now then.

**Comment by kaspar-allenbach** [comment]
Heads-Up for your information:

I consider the above code not working.
I just can't see trough the API patterns of Instagram.

* Sometimes there are 3 images displayed and sometimes only 2.
No correlations with hashtags whatsoever
* The set of images seems to be displayed at random. No pattern there.
* As soon as I remove the conditional all is fine.

Here'se the page: https://leariba.ch/images

**Comment by johnfmorton** [comment]
Hello Kaspar,

Did you see the FAQ portion of the docs? 

https://github.com/jmx2inc/picpuller-for-craft3/blob/v3/PicPullerDocumentation.md#faqs

> Unexpected number of images returned
> The number of images returned from a Pic Puller loop can be up to 32 images in most cases, but it's not guaranteed. Why is that? It has to do with how the Instagram API returns data. Although I've not read it in official documentation, it appears whatever number of images you request are returned from the API and then that set of images is filtered for images that may have been deleted by users. For example, if I were pulling 3 images from my Instagram feed, I would expect 3 images returned in my Pic Puller loop in Craft. If I went into my Instagram app on my phone and deleted the most recent photo I've taken, I would then only receive 2 images back in my Craft site.

Does that answer your question?

**Comment by kaspar-allenbach** [comment]
Yes. I've read that. But my client assured me that she didn't delete any photos. (Yes, we know how reliable these informations are 😜). I then suspected that images which the hashtag was applied after uploading wouldn't count as well. But this doesn' seem to apply either.

My last idea would be to write the hashtags as css classes and then just hidde them in the frontend via `display:none`.

**Comment by johnfmorton** [comment]
I believe your client! 👍 What's I'm telling you is _not_ from the Instagram API documentation. Their documentation is sparse and not well maintained. (See: https://www.instagram.com/developer/endpoints/#limits then click the link for more information. Dead link.)

I think you are correct that hashtags applied after the initial posting to Instagram (i.e. added in a subsequent comment to a posting) do not get included in the API's retrieval of information about an image or video. This feels like an error in the API, but unfortunately, it's not something we can change.

I don't understand your idea about writing hashtags as css classes and hiding them. What are you trying to do? Why not just display the last 3 images from the feed?

**Comment by kaspar-allenbach** [comment]
I tought about writing something like this:

**HTML**
```
<div class="hashtagX hastagY hashtagZ">
  <img src="superfancyinstaimg.jpg">
</div>

<div class="hashtagX">
  <img src="superfancyinstaimg.jpg">
</div>
```

and then in the CSS:

**CSS**
```
.hashtagY {
  display:none;
}
```

Do you understand the idea. This would hide the images with the hashtagY in the frontend instead of the backend. I think this should work, right?

**Comment by johnfmorton** [comment]
The problem I think you will have is this:

If your client adds `hashtagY` to an image after the image is posted, the `hashtagY` will not be reported to you by the Instagram API. That could leave _some_ images showing up on the site even though your client has added the hashtag to it that is supposed to hide it from your site.

**Comment by kaspar-allenbach** [comment]
Yeah right, those would show up no matter what. I'll discuss this with my client. I think leaking instagram images ar not the most sensitive of data. If there is one unprefered image personaly I could live with that, but that's not up for me to decide. The only other option would be to just abandone the whole idea and add a classic Craft upload field and let my client upload the images manually trough the CP.

Thanks for your helpfulness anyways 🎉

**Comment by johnfmorton** [comment]
Anytime.
