### ISSUE TITLE
Instagram Authorized App but not displaying in Craft

### ISSUE THREAD

**Issue by DaroldFletcher** [jmx2inc/picpuller-for-craft3#14]
I went through the steps to authorize a user (second user). Instagram is showing that the app is authorized. However, it does not show that authorization in Craft. It keeps repeatedly asking me to authorize.

**Comment by johnfmorton** [comment]
I'm sorry you're having issues, Darold. Can you tell me which version of Pic Puller you're using and which version of Craft?

**Comment by johnfmorton** [comment]
Just for reference, on my own multi-user site, I'm on Craft CMS 3.1.14 with Pic Puller 3.0.15.

**Comment by DaroldFletcher** [comment]
I'm on Craft Pro 3.0.11 and Pic Puller 3.0.13.2.

**Comment by johnfmorton** [comment]
Thanks. I wouldn’t expect any issue based on what I know so far.

In your browser, can you open the inspector (so you can see Javascript errors), and then try to authorize that user again? Do you see any Javascript errors that might be helpful?

**Comment by DaroldFletcher** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
auth:231 I heard back from the post action
auth:232 response: null
auth:233 Uncaught TypeError: Cannot read property 'success' of null
    at auth:233
    at Object.error (Craft.js:361)
    at c (jquery.js:3317)
    at Object.fireWith [as rejectWith] (jquery.js:3447)
    at l (jquery.js:9274)
    at XMLHttpRequest.<anonymous> (jquery.js:9514)

**Comment by johnfmorton** [comment]
Interesting. _Something_ isn’t loading. Do you have this on a staging and production server? Is this behavior happening in both locations?

**Comment by DaroldFletcher** [comment]
Yes. I'm getting the error in both environments. Here is the stacktrace for the resource that's not loading
[400 Bad Request.pdf](https://github.com/jmx2inc/picpuller-for-craft3/files/2913003/400.Bad.Request.pdf)

**Comment by johnfmorton** [comment]
It looks like you're not getting data back from the Authorization process. Added to that, it then appears I check for a "response" but not the "success" property on the response. 

I don't expect this to be a total fix, but I've made a change to the 'auth' file on line 21 in the develop branch. You can see the change here:

https://github.com/jmx2inc/picpuller-for-craft3/blob/develop/src/templates/auth/index.twig#L21

Can you update that line in your staging site and then let me know what you see in the console when you try to authenticate?

**Comment by DaroldFletcher** [comment]
When I tried doing that, I got the same error message as stated above. The message feels stays "Loading" and doesn't get updated with either of the conditionals. 

However, I updated to the auth file to display the user id, instagram id, and oauth to the console. Can I just insert that information into the craft_picpuller_authorizations table or are there other things that need to get updated?

**Comment by johnfmorton** [comment]
You can try to update the database with the info. The "uid" is automatically generated by Craft though. See my screenshot.

http://share.jmx2.com/GyZy3Y

I'm not sure what you'd do for that field, unfortunately. 

Manually updating the database obviously not solving the underlying problem though. 

Do you also have this site in a local environment? Is the same thing happening there? I'm still stumped as to what's actually happening here. I'd like to track what's going on here.

**Comment by johnfmorton** [comment]
I also wonder if this is related to this user being authenticated only or does this affect all Instagram accounts.

**Comment by DaroldFletcher** [comment]
The issue is happening in my local environment. That is where I updated the auth file to get the actual authentication information. I've tried with a couple of Instagram accounts with different craft users accounts, so it doesn't seem to be confined to a specific user or Instagram account.

The developer that added the first account is no longer around. It was before the upgrade to Craft 3, obviously using a previous version of pic puller. I may need to reach out to him to see if he had a similar issue.

**Comment by johnfmorton** [comment]
Maybe send me an email and we can go back and forth and figure it out. 

Your early error still interests me.

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
auth:231 I heard back from the post action1
```

That makes me wonder if the action expecting the post data just isn't working at all. I don't know why that would be though.

**Comment by johnfmorton** [comment]
Another thought based on you having updated this from Craft 2 to Craft 3...

On your local environment (with a database backup) can you uninstall Pic Puller completely and then reinstall?

**Comment by DaroldFletcher** [comment]
Inserting the record directly into the table seems to work, even though the uid=0. I'm not sure what that does.

However, to your point, this is a workaround and the real issue should be addressed. I'll send you an email later today so we can figure it out.

**Comment by DaroldFletcher** [comment]
Hi John,

I just wanted to follow-up with you. I have uninstalled and reinstalled the plug-in and it seems to be working fine now. I'm not sure what happened, but all is well.

Thanks,

Darold

**Comment by johnfmorton** [comment]
Thanks for the follow-up, Darold.
