### ISSUE TITLE
[Enhancement/Feature] Have more than one Instagram account per User ?

### ISSUE THREAD

**Issue by Totemika** [jmx2inc/picpuller-for-craft3#4]
Hi!
I'm trying out this plugin to see if It fits in my scenario; I'm having multiple sites. If I want to have an Instagram feed embedded in the primary site everything is fine and we can use this for a while, but I'll eventually need to be able to show a **different Instagram feed per site** (each site has a different sub-brand with a different Instagram account) without the need of having to create a **user for each site**. Is this possible out of the box? If not, do you think it's a reasonably feasible implementation with the current code base?
Thank you.

**Comment by johnfmorton** [comment]
It does not work as you wish out of the box. A Craft user has a single Instagram account and authorization associated with it. Different Craft users can have different Instagram account associated with them, but a single Craft user can have only one. 

I think you are asking for a single user to have different Instagram credentials based on what site they are viewing. Implementing that is not an easy change IMO.

**Comment by Totemika** [comment]
Ok, thank you for your answer, we may go with this one to start, only thing is that we'd need to create a "ghost" user per site.

**Comment by johnfmorton** [comment]
Sounds good. Thanks and good luck!
