### ISSUE TITLE
Can't get Username to display

### ISSUE THREAD

**Issue by brandondeweese** [jmx2inc/picpuller-for-craft3#7]
Did something change? Username is not displaying... Followed your code and can't get it to work. Attached is error. Captions, created_time all work fine.
![screen shot 2018-11-09 at 3 27 40 pm](https://user-images.githubusercontent.com/18017918/48293478-24b3de00-e434-11e8-948e-c6f512afac24.png)

**Comment by johnfmorton** [comment]
Which function are you using?

**Comment by brandondeweese** [comment]
Yea, I was using recent media... Can't believe I missed that! Figured it out.. thanks!

**Comment by johnfmorton** [comment]
No problem! Glad it’s working.
