### ISSUE TITLE
Not using cached data after api limit is reached

### ISSUE THREAD

**Issue by lukermiller** [jmx2inc/picpuller-for-craft3#8]
Once the API limit of 200 per hour is reached. I receive the error message 
Error Type: OAuthRateLimitException
Error Message: You have exceeded the maximum number of requests per hour

I have use_stale_cache set to true.
I was under the assumption that once this limit is reached it would be using cached data if this was set to true.

**Comment by johnfmorton** [comment]
Pic Puller attempts to do that, but if the request doesn't match the URL of the request exactly, it won't return a result. I suggest using the built-in Craft `{cache}` tags plus have an "error" block that displays backup content as well.

**Comment by lukermiller** [comment]
Thanks.
Using the built in Craft Cache will work perfectly.

**Comment by johnfmorton** [comment]
Thanks. Good luck!
