### ISSUE TITLE
Filter media with certain hashtag

### ISSUE THREAD

**Issue by kaspar-allenbach** [jmx2inc/picpuller-for-craft3#9]
Hi John.

You write in the doc's

> There is no "hashtag" searching available, even for tags in your own media.

But is it still possible to display only media with a certain hashtag?

Something like:
```
{% for instagramdata in craft.picPuller.user({'use_stale_cache' : true, 'user_id' : 1 }) %}

    {% if 'myhashtag' in [instagramdata.tags] %}

       {# only media with the hashtag 'myhashtag' is displayed #}

   {% endif %}

{% endfor %}

```

Is omething like this possible?

**Comment by johnfmorton** [comment]
Yes, I believe that will work. You just can't ask the Instagram API for a particular hashtag anymore.
